server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: WorkoutService
          uri: http://localhost:8081  # replace with the actual URL of your service
          predicates:
            - Path=/workoutgroups/**
        - id: ExerciseService
          uri: http://localhost:8082  # replace with actual URL
          predicates:
            - Path=/exercises/**
